apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: mydatabase
  DB_HOST: 10.100.136.226
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: bXl1c2VyCg==
  DB_PASSWORD: bXlwYXNzd29yZAo=